module.exports = {
  STUDENT_ROLE: 0,
  VOLUNTEER_ROLE: 1,
  SUB_CLASS_MONITOR: 2,
  CLASS_MONITOR: 3,
  SUPER_ADMIN: 4,
  DEFAULT_AVATAR_PATH: "https://thanhnth.blob.core.windows.net/avatars/",
  DEFAULT_CV_PATH: "https://thanhnth.blob.core.windows.net/cv-data/",
  CV_FOLDER_PATH: "https://thanhnth.blob.core.windows.net/cv-data/",
  AUDIO_FOLDER_PATH: "https://thanhnth.blob.core.windows.net/cv-data/",
  AVATAR_FOLDER_PATH: "https://thanhnth.blob.core.windows.net/avatars/",
  WEEKDAY: [
    { key: 0, value: "all", text: "all" },
    { key: 1, value: "Sun", text: "Chủ Nhật" },
    { key: 2, value: "Mon", text: "Thứ Hai" },
    { key: 3, value: "Tue", text: "Thứ Ba" },
    { key: 4, value: "Wed", text: "Thứ Tư" },
    { key: 5, value: "Thu", text: "Thứ Năm" },
    { key: 6, value: "Fri", text: "Thứ Sáu" },
    { key: 7, value: "Sat", text: "Thứ Bảy" },
  ],
  NOON_TIME: [
    {
      key: 0,
      value: "morning",
      text: "Sáng",
      startTime: "8:00",
      endTime: "11:00",
    },
    {
      key: 1,
      value: "afternoon",
      text: "Chiều",
      startTime: "13:00",
      endTime: "16:00",
    },
    {
      key: 2,
      value: "evening",
      text: "Tối",
      startTime: "19:00",
      endTime: "22:00",
    },
  ],
  LESSON_SCHEDULE: 0,
  INTERVIEW_SCHEDULE: 2,
  NOTI_TYPE: {
    NOTI_CV: 0,
    NOTI_REMIND_SET_MONITOR: 1,
    NOTI_SET_INTERVIEW_PARTICIPANT: 2,
    NOTI_UPGRADE_MONITOR_ROLE: 3,
    NOTI_DOWNGRADE_MONITOR_ROLE: 4,
    NOTI_INCHARGE_LESSON: 5,
  },
  NOTI_PATH: {
    NOTI_CV: "cv",
    NOTI_CLASS: "classes",
    NOTI_SET_INTERVIEW_PARTICIPANT: "cv",
    NOTI_UPGRADE_MONITOR_ROLE: "classes",
    NOTI_DOWNGRADE_MONITOR_ROLE: "classes",
  },
};
